"use strict";

/** Stabilni kodi za `error.code` v JSON odgovorih. */
module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMIT: "RATE_LIMIT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PROFILE_BLOCKED: "PROFILE_BLOCKED",
  USER_SUSPENDED: "USER_SUSPENDED",
  PROFANITY_BLOCKED: "PROFANITY_BLOCKED",
  DUPLICATE_CONTENT: "DUPLICATE_CONTENT",
  CONTENT_FLOOD: "CONTENT_FLOOD",
  LINK_SPAM: "LINK_SPAM",
  REPEAT_SPAM: "REPEAT_SPAM",
  ADMIN_REQUIRED: "ADMIN_REQUIRED",
};
